### ISSUE TITLE
我发现一个问题，azure，30g硬盘可以创建debian10,29g就不行了，是否是azure的bug？

### ISSUE THREAD

**Issue by kyohan789** [testnobody/azure-manager#2]
我发现一个问题，azure，30g硬盘可以创建debian10,29g就不行了，是否是azure的bug？

**Comment by kyohan789** [comment]
1，能否加入，账号状态检查功能，被封了没有？
2，能否加入，账号的余额查询功能？
3，能否加入，其他地区创建机器，比如英国，巴西，等等？

**Comment by kyohan789** [comment]
请问你有联系方式吗？加个聊天工具，
heroku，无法创建虚拟机，新的脚本：
Internal Server Error
The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

**Comment by testnobody** [comment]
> 请问你有联系方式吗？加个聊天工具，
> heroku，无法创建虚拟机，新的脚本：
> Internal Server Error
> The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

请描述下具体所开机型型号，硬盘大小等信息，此外如果heroku长时间未操作进入休眠状态也会出现404，可以从主页重新进入操作
