### ISSUE TITLE
heroku，无法创建虚拟机，新的脚本： Internal Server Error 发现是账号已经被封了，已经解决！

### ISSUE THREAD

**Issue by kyohan789** [testnobody/azure-manager#4]
heroku，无法创建虚拟机，新的脚本：
Internal Server Error
The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

**Comment by testnobody** [comment]
订阅禁用 账号被 API失效都会引起404 ，后面会考虑加入订阅状态查询
