### ISSUE TITLE
能否加入debian 11系统的创建？

### ISSUE THREAD

**Issue by moranno** [testnobody/azure-manager#7]
这个机器应该是最合适我目前需求的，请问能否加入？

**Comment by moranno** [comment]
update: 尝试编辑vm.html加入了b1ms机器的创建, 且测试成功 <option value="Standard_B1ms">B1ms</option>

请问题: 如何加入debian 11系统的创建呢? 按模板加入<option value="debian11">debian11</option>, 并不生效,创建出来的是ubuntu 18系统.

**Comment by testnobody** [comment]
还要再这里修改增加选项，具体系统命名参考下azure系统命名规则
https://github.com/testnobody/azure-manager/blob/23c731d56eb488af5d7f1b45541b60440de9fd10/function.py#L96

**Comment by moranno** [comment]
> 还要再这里修改增加选项，具体系统命名参考下azure系统命名规则
> 
> https://github.com/testnobody/azure-manager/blob/23c731d56eb488af5d7f1b45541b60440de9fd10/function.py#L51

感谢，搞定了，最近发现“删除虚拟机”不生效。是不是API接口有变化？
